app = "mango-fills"
kill_signal = "SIGTERM"
kill_timeout = 30

[build]
  dockerfile = "../Dockerfile"

[experimental]
  cmd = ["service-mango-fills", "fills-config.toml"]

[metrics]
  path = "/metrics"
  port = 9091
