app = "mango-orderbook"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../Dockerfile"

[experimental]
  cmd = ["service-mango-orderbook", "orderbook-config.toml"]

[metrics]
  path = "/metrics"
  port = 9091
