app = "mango-pnl"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../Dockerfile"

[experimental]
  cmd = ["service-mango-pnl", "pnl-config.toml"]

[metrics]
  path = "/metrics"
  port = 9091
